APP_TOKEN: Token
PARTIALS:
  - MESSAGE
  - CHANNEL
  - REACTION
INTENTS:
  - GUILDS
  - GUILD_EMOJIS_AND_STICKERS
  - GUILD_MESSAGES
  - GUILD_MESSAGE_REACTIONS
  - GUILD_MESSAGE_TYPING

MESSAGE_COMMANDS:
  APP_PREFIX: !
  COMMAND_AUTO_REMOVE: false
